LunchCommand/Controllers/LunchesController.cs
using System.Linq;
using System.Web.Mvc;

namespace LunchCommand.Controllers
{
    [Authorize]
    public class LunchesController : BaseAuthenticatedController
    {
        // GET: Lunches
        public ActionResult Index()
        {
            return View(this.LunchUser.Team.Lunches.OrderByDescending(l=>l.LunchTimeUtc).ToArray());
        }
    }
}

LunchCommand/Controllers/TeamsController.cs
using System;
using System.Net;
using System.Web.Mvc;
using LunchCommand.Core.Models;
using LunchCommand.ViewModels;
using LunchCommand.Services;
using LunchCommand.Core.Models.Data;

namespace LunchCommand.Controllers
{
    public class TeamsController : BaseAuthenticatedController
    {
        private readonly ITeamRepository teamRepo;
        private readonly IInviteRepository inviteRepo;
        private readonly IReCaptchaService recaptchaService;

        public TeamsController(ITeamRepository teamRepo, IInviteRepository inviteRepo, IReCaptchaService recaptchaService) : base(false)
        {
            this.teamRepo = teamRepo;
            this.inviteRepo = inviteRepo;
            this.recaptchaService = recaptchaService;
        }

        // GET: Teams/Create
        [AllowAnonymous]
        public ActionResult Create()
        {
            return View(new TeamViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public ActionResult Create(TeamViewModel teamModel)
        {
            if (ModelState.IsValid)
            {
                var team = this.teamRepo.FindByName(teamModel.Name);

                if (!this.recaptchaService.ValidateReCaptcha(this.Request))
                {
                    this.ModelState.AddModelError(String.Empty, "Could not validate reCAPTCHA.  Please try again.");
                }
                else if (team != null && team.TeamId != this.LunchUser.TeamId)
                {
                    this.ModelState.AddModelError(nameof(TeamViewModel.Name), "A team with that name already exists");
                }
                else if (teamModel.ParsedTime == null || teamModel.ParsedTime.Value.TotalHours >= 24 || teamModel.ParsedTime.Value.TotalHours <= 0)
                {
                    this.ModelState.AddModelError(nameof(TeamViewModel.LunchStartTimeUtc), "Please enter a start time in format \"HH:MM AM/PM\" or \"HH:MM\"");
                    return View(teamModel);
                }

                else
                {
                    team = new Team();
                    teamModel.UpdateTeam(team);
                    team.AdminRole = new Role() { Name = String.Format(team.Name + "Team Administrator") };
                    this.teamRepo.Save(team);

                    var invite = inviteRepo.Generate(team);

                    return RedirectToAction("Created", new { inviteCode = invite.InviteCode });
                }
            }

            return View(teamModel);
        }

        [AllowAnonymous]
        public ActionResult Created(String inviteCode)
        {
            this.ViewBag.InviteCode = inviteCode;
            return this.View();
        }

        [Authorize]
        // GET: Teams/Edit/5
        public ActionResult Edit()
        {
            if (this.UserIsTeamAdmin)
            {
                return View(new TeamViewModel(this.LunchUser.Team));
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit(TeamViewModel team)
        {
            if (!this.UserIsTeamAdmin)
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }

            if (ModelState.IsValid && team.TeamId == this.LunchUser.TeamId && this.UserIsTeamAdmin)
            {
                var oldTeam = this.teamRepo.FindByName(team.Name);
                if (oldTeam != null && oldTeam.TeamId != team.TeamId)
                {
                    this.ModelState.AddModelError("name", "A team with that name already exists");
                    return View(team);
                }
                if (team.ParsedTime == null || team.ParsedTime.Value.TotalHours >= 24 || team.ParsedTime.Value.TotalHours <= 0)
                {
                    this.ModelState.AddModelError("LunchStartTime", "Please enter a start time in format \"HH:MM AM/PM\" or \"HH:MM\"");
                    return View(team);
                }

                oldTeam = this.teamRepo.FindById(team.TeamId);
                team.UpdateTeam(oldTeam);

                this.teamRepo.Save(oldTeam);
                return RedirectToAction("Index", "Home");
            }
            return View(team);
        }

        public ActionResult Members()
        {
            if (!this.UserIsTeamAdmin)
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }

            return View("Members");
        }
    }
}

LunchCommand/Controllers/UsersController.cs
using System.Linq;
using System.Web.Mvc;
using System.Web.Routing;

namespace LunchCommand.Controllers
{
    [Authorize]
    public class UsersController : BaseAuthenticatedController
    {
        protected override void Initialize(RequestContext requestContext)
        {
            base.Initialize(requestContext);
        }

        public ActionResult Index()
        {
            return this.View(this.LunchUser.Team.Users.OrderByDescending(u => u.LunchesDecided.Count(l => l.Decision)).ToArray());
        }
    }
}

LunchCommand/Controllers/VenuesController.cs
using System.Linq;
using System.Net;
using System.Web.Mvc;
using LunchCommand.Core.Models;
using LunchCommand.ViewModels;
using LunchCommand.Core.Models.Data;

namespace LunchCommand.Controllers
{
    [Authorize]
    public class VenuesController : BaseAuthenticatedController
    {
        private readonly IGenreRepository genreRepository;
        private readonly IVenueRepository venueRepositiory;

        public VenuesController(IGenreRepository genreRepository, IVenueRepository venueRepositiory)
        {
            this.genreRepository = genreRepository;
            this.venueRepositiory = venueRepositiory;
        }

        // GET: Venues
        public ActionResult Index()
        {
            var venues = this.LunchUser.Team.ActiveVenues;
            return View(venues.ToList());
        }

        // GET: Venues/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id != null)
            {
                var venue = this.venueRepositiory.FindById(id.GetValueOrDefault());
                if (venue == null)
                {
                    return HttpNotFound();
                }

                if (venue.SharesTeamWith(this.LunchUser))
                {
                    ViewBag.GenreID = new SelectList(this.genreRepository.FindAll(), "GenreID", "Name", venue.GenreID);
                    return View(new VenueViewModel(venue));
                }
            }

            ViewBag.GenreID = new SelectList(this.genreRepository.FindAll(), "GenreID", "Name", null);
            return this.View(new VenueViewModel(new Venue()) { VenueId = -1 });
        }

        // POST: Venues/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(VenueViewModel venueModel)
        {
            if (ModelState.IsValid)
            {
                if (venueModel.VenueId >= 0)
                {
                    var venue = this.venueRepositiory.FindById(venueModel.VenueId);
                    if (venue.SharesTeamWith(this.LunchUser))
                    {
                        venueModel.UpdateModel(venue);
                        this.venueRepositiory.Save(venue);
                    }
                }
                else
                {
                    var venue = new Venue();
                    venue.Team = this.LunchUser.Team;
                    venue.CreatedBy = this.LunchUser;
                    venueModel.UpdateModel(venue);
                    this.venueRepositiory.Save(venue);
                }

                return RedirectToAction("Index");
            }
            ViewBag.GenreID = new SelectList(this.genreRepository.FindAll(), "GenreID", "Name", venueModel.GenreID);
            return View(venueModel);
        }

        // GET: Venues/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Venue venue = this.venueRepositiory.FindById(id.GetValueOrDefault());
            if (venue == null)
            {
                return HttpNotFound();
            }
            return View(venue);
        }

        // POST: Venues/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Venue venue = this.venueRepositiory.FindById(id);

            if (venue.SharesTeamWith(this.LunchUser))
            {
                venue.Deleted = true;
                this.venueRepositiory.Save(venue);
            }

            return RedirectToAction("Index");
        }
    }
}

LunchCommand/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="~/favicon.ico" />
    <script src='https://www.google.com/recaptcha/api.js'></script>

    <title>@(ViewBag.Title.Length > 1 ? ViewBag.Title + " - " : "")Lunch Command</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Scripts/jquery-ui-tooltips/jquery-ui.css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("styles", false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><span class="glyphicon glyphicon-arrow-down"></span></button>
                @if (ViewBag.DisplayNavbar == null || ViewBag.DisplayNavbar)
                {
                    <a href="@Url.Action("Index", "Home")"><span class="navbar-brand">Lunch Command</span> <img class="navbar-brand" src="~/Content/bgr.png" height="30" /></a>
                }
                else
                {
                    <span class="navbar-brand">Lunch Command</span>
                }
            </div>@if (ViewBag.DisplayNavbar == null || ViewBag.DisplayNavbar)
            {
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Manage Venues", "Index", "Venues")</li>
                        <li>@Html.ActionLink("Historic Lunches", "Index", "Lunches")</li>
                        <li>@Html.ActionLink("Luncher Leaderboards", "Index", "Users")</li>
                        <li>@Html.ActionLink("Invite Others", "Send", "Invitations")</li>
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            }
        </div>
    </div>
    <div class="layout-body container body-content">        
        @if (ViewBag.TeamName != null)
        {
        <div class="team-header">
            <span style="font-size: small" class="text text-muted">Team:&nbsp;</span>
            <span style="font-size: x-large" class="text text-muted">@ViewBag.TeamName</span>
            @if (ViewBag.UserIsTeamAdmin == true){
                <a style="font-size: small" href="@Url.Action("Edit", "Teams")">(manage)</a>
            }
        </div>
        }
        @RenderBody()
        <hr />
        <footer>
            <p>
                LunchCommand version @ViewBag.Version    |   Source code available at <a href="https://bitbucket.org/nathandaniels/lunch-command/src/">Bitbucket</a>
                <br />  &copy; @DateTime.Now.Year Nathan Daniels.  |  Glyphs from <a href="http://glyphicons.com/">Glyphicons</a>
            </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/jquery-ui-tooltips/jquery-ui.js")
    @Scripts.Render("~/Scripts/knockout/knockout.js")
    @Scripts.Render("~/Scripts/LunchCommand.js")

    <script>
        LunchCommand.BaseService.BaseUrl = "@Url.Content("~/api/")";
    </script>

    @RenderSection("scripts", required: false)

    @if (ViewBag.Authenticated && ViewBag.NotificationListenerEnabled)
    {
        <script>
            var notificationService = new LunchCommand.NotificationsListener('@Url.Content("~/Content/bgr.png")');
            notificationService.begin();
        </script>
    }

</body>
</html>

LunchCommand/Views/Shared/_reCAPTCHA.cshtml
<div class="g-recaptcha" data-sitekey="6Lf1GRkTAAAAANduFvlkfxRW7Q37m8K-M8e2TaOY"></div>